// メイン画面に出す固定の文字（ここ以外で画面の文言を増やさない）。
// 金額・日付・件数・店名などのデータは含めない。
// 状態によって置き換わる語は、元の語と同じ位置・同じか短い字数にする。

export const T = {
  nav: {
    label: 'メイン',
    home: 'ホーム',
    expenses: '明細',
    futari: 'ふたり',
  },
  home: {
    title: '家計簿',
    household: 'ふたり',
    guest: 'ゲスト',
    remaining: '予算残り',
    over: '予算超過',
    review: '要確認',
    recent: '最近の明細',
    connectionError: '接続エラー',
  },
  expenses: {
    title: '明細',
    all: 'すべて',
    pending: '要確認',
    advance: '立替',
    counted: '予算に計上済み',
    uncounted: '予算外',
    confirm: '確認',
    empty: '明細なし',
  },
  split: {
    shared: '共同費',
    personal: '除外',
    advance: '立替中',
    settled: '精算済み',
  },
  futari: {
    title: 'ふたり',
    heading: '今月の精算',
    half: '折半',
    advanceOf: 'の立替',
    breakdown: '内訳',
    settle: '精算を記録',
  },
  // アイコンだけのボタンのアクセシブルネーム（画面には出さない）
  aria: {
    settings: '設定',
    search: '検索',
    detail: '詳細',
    edit: '編集',
    prevMonth: '前の月',
    nextMonth: '次の月',
    close: '閉じる',
    back: '戻る',
    retry: '再試行',
  },
  // シート（タップ後に開く詳細）の見出しと短い語。説明文は置かない
  sheet: {
    period: '期間',
    settings: '設定',
    guest: 'ゲスト',
    household: 'ふたり',
    thisPeriod: '今月',
    periodSettings: '期間の設定',
    startDay: (day: number) => `${day}日起算`,
    members: 'メンバー',
  },
  // 明細の詳細シート（行・⋯ から開く）
  detail: {
    date: '日付',
    category: 'カテゴリ',
    split: '区分',
    advanceBy: '立替',
    input: '入力',
    payer: '支払い',
    group: 'グループ',
    groupFallback: 'LINE',
    items: '商品',
    receipt: 'レシート',
    attach: 'レシート添付',
    include: '予算に含める',
    confirm: '確認',
    edit: '編集',
    delete: '削除',
    deleteConfirm: '削除する',
  },
  // 編集シート（鉛筆・詳細の編集・LINE の「修正」リンク）
  edit: {
    title: '編集',
    description: '説明',
    amount: '金額',
    date: '日付',
    category: 'カテゴリ',
    payer: '支払い者',
    include: '予算に含める',
    save: '保存',
    cancel: 'キャンセル',
  },
  receipt: {
    title: 'レシート',
    replace: '差し替え',
    open: '開く',
  },
  // 検索・絞り込みシート（明細の検索ボタン）
  filter: {
    title: '検索',
    budget: '予算',
    all: 'すべて',
    included: '含む',
    excluded: '除外',
    category: 'カテゴリ',
    sort: '並び',
    sortDate: '日付',
    sortAmount: '金額',
    summary: '集計',
    count: '件数',
    total: '合計',
    excludedCount: '除外',
    clear: 'クリア',
    items: (n: number) => `${n}件`,
  },
  // 予算シート（ホームの「予算残り」から開く。刷新前のホームの分析をここに集める）
  budget: {
    title: '予算',
    spent: '今月の支出',
    count: '支出回数',
    countValue: (n: number) => `${n}回`,
    dailyAverage: '1日平均',
    progress: '予算進捗',
    remaining: '残り',
    over: '超過',
    perDay: 'あと使える / 日',
    daysLeft: (n: number) => `残り${n}日`,
    mom: '前月比',
    prev: '前月',
    monthly: '月間予算',
    paceGood: '順調',
    paceWarning: 'やや超過',
    paceDanger: '超過',
    paceUnset: '未設定',
    categories: 'カテゴリ別',
    catRemaining: '残',
    catOver: '超',
    catUnset: '予算未設定',
    byCategory: 'カテゴリ別支出',
    daily: '日別の推移',
  },
  settings: {
    title: '設定',
    tabBudget: '予算',
    tabPeriod: '期間',
    tabDisplay: '表示',
    monthlyBudget: '月間予算',
    alert: '残り警告',
    categoryBudgets: 'カテゴリ別',
    total: '合計',
    modeMonthly: '月単位',
    modeCustomStart: '指定日起算',
    modeCustom: '期間指定',
    startDay: '起算日',
    dayOption: (day: number) => `${day}日`,
    startDate: '開始日',
    endDate: '終了日',
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    themeSystem: '自動',
    links: 'その他',
    terms: '利用規約',
    privacy: 'プライバシー',
    save: '保存',
    saved: '保存済み',
    signedOut: '未ログイン',
  },
  // トーストは 8 字以内の短い語だけ（説明文にしない）
  toast: {
    forbidden: '権限なし',
    network: '通信エラー',
    busy: '混雑中',
    failed: '失敗',
    settled: '精算済み',
  },
} as const;

export type ToastKey = keyof typeof T.toast;
