#!/usr/bin/env node

/**
 * MCP-based AI Code Review Script
 *
 * このスクリプトは、Claude Code (MCP) を使用して:
 * 1. PRの差分を取得
 * 2. Claude APIでコードレビュー
 * 3. GitHub MCPでコメント＆Issue作成
 *
 * 環境変数:
 * - ANTHROPIC_API_KEY: Claude API Key
 * - GITHUB_TOKEN: GitHub Personal Access Token
 * - GITHUB_REPOSITORY: owner/repo
 * - PR_NUMBER: Pull Request番号
 */

import Anthropic from "@anthropic-ai/sdk";
import { Octokit } from "@octokit/rest";

// 環境変数チェック
const requiredEnvVars = ["ANTHROPIC_API_KEY", "GITHUB_TOKEN", "GITHUB_REPOSITORY", "PR_NUMBER"];
for (const envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    console.error(`❌ Error: ${envVar} is not set`);
    process.exit(1);
  }
}

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
const prNumber = parseInt(process.env.PR_NUMBER, 10);

console.log(`🔍 Reviewing PR #${prNumber} in ${owner}/${repo}`);

// ========================================
// Step 1: PRの差分を取得
// ========================================
console.log("📥 Fetching PR diff...");
const { data: pr } = await octokit.pulls.get({
  owner,
  repo,
  pull_number: prNumber,
});

const { data: files } = await octokit.pulls.listFiles({
  owner,
  repo,
  pull_number: prNumber,
});

// 差分をテキスト形式で構築
let diffText = `# PR #${prNumber}: ${pr.title}\n\n`;
diffText += `**Author**: ${pr.user.login}\n`;
diffText += `**Branch**: ${pr.head.ref} → ${pr.base.ref}\n\n`;
diffText += `## Changed Files (${files.length})\n\n`;

for (const file of files) {
  diffText += `### ${file.filename} (+${file.additions}/-${file.deletions})\n`;
  diffText += `\`\`\`diff\n${file.patch || "Binary file"}\n\`\`\`\n\n`;
}

// ========================================
// Step 2: Claude APIでコードレビュー
// ========================================
console.log("🤖 Analyzing code with Claude...");

const reviewPrompt = `あなたは経験豊富なシニアエンジニアです。以下のGitHub Pull Requestを詳細にレビューしてください。

**レビュー観点:**
1. 🐛 **バグリスク**: 潜在的なバグや論理エラー
2. 🔒 **セキュリティ**: セキュリティ脆弱性や機密情報の漏洩
3. 🚀 **パフォーマンス**: 効率の悪いコードやボトルネック
4. 📖 **可読性**: コードの可読性や保守性
5. ✨ **ベストプラクティス**: TypeScript/React/Node.jsのベストプラクティス

**レビュー形式:**
- 各観点ごとに箇条書きで指摘
- 重大な問題には 🔴、軽微な問題には 🟡 をつける
- 具体的なファイル名と行数を記載
- 改善提案も含める

**出力形式:**
マークダウン形式で、GitHub PRコメントとして投稿できる内容にしてください。

---

${diffText}`;

const message = await anthropic.messages.create({
  model: "claude-sonnet-4-20250514",
  max_tokens: 4096,
  messages: [
    {
      role: "user",
      content: reviewPrompt,
    },
  ],
});

const reviewContent = message.content[0].type === "text"
  ? message.content[0].text
  : "レビューの生成に失敗しました";

console.log("✅ Code review completed");

// ========================================
// Step 3: PRにコメント投稿
// ========================================
console.log("💬 Posting review comment...");

const commentBody = `## 🤖 Claude Code Review

${reviewContent}

---
<sub>Powered by Claude Sonnet 4 via MCP | Generated at ${new Date().toISOString()}</sub>`;

await octokit.issues.createComment({
  owner,
  repo,
  issue_number: prNumber,
  body: commentBody,
});

console.log("✅ Review comment posted");

// ========================================
// Step 4: 重大な問題がある場合はIssue作成
// ========================================
const hasCriticalIssues = /🔴|重大|セキュリティ|脆弱性|バグ|critical|security|vulnerability/i.test(reviewContent);

if (hasCriticalIssues) {
  console.log("🚨 Critical issues detected, creating GitHub Issue...");

  // レビュー内容から重大な問題を抽出
  const criticalSections = reviewContent
    .split("\n")
    .filter(line => /🔴|重大|セキュリティ|脆弱性|critical|security/i.test(line));

  const issueBody = `## 🚨 AI Code Review で重大な問題が検出されました

PR #${prNumber} のレビュー中に、以下の重大な問題が見つかりました:

${criticalSections.join("\n")}

---

### 📋 関連情報
- **PR**: #${prNumber}
- **ブランチ**: ${pr.head.ref}
- **作成者**: @${pr.user.login}

### 🔗 レビュー全文
${commentBody}

---
<sub>🤖 Auto-generated by Claude Code Review | ${new Date().toISOString()}</sub>`;

  const issue = await octokit.issues.create({
    owner,
    repo,
    title: `🚨 [AI Review] PR #${prNumber} に重大な問題が検出されました`,
    body: issueBody,
    labels: ["ai-review", "critical", "needs-attention"],
  });

  console.log(`✅ Issue created: #${issue.data.number}`);

  // PRにIssueへのリンクを追加コメント
  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: `⚠️ **重大な問題が検出されたため、Issue #${issue.data.number} を作成しました**`,
  });
} else {
  console.log("✅ No critical issues detected");
}

// ========================================
// Step 5: サマリー出力
// ========================================
console.log("\n📊 Review Summary:");
console.log(`- PR: #${prNumber}`);
console.log(`- Files changed: ${files.length}`);
console.log(`- Lines added: +${pr.additions}`);
console.log(`- Lines deleted: -${pr.deletions}`);
console.log(`- Critical issues: ${hasCriticalIssues ? "Yes 🔴" : "No ✅"}`);
console.log("\n🎉 MCP-based code review complete!");
