name: Deploy to Development

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  NODE_VERSION: '20'

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies (Bot)
      run: |
        cd bot
        npm ci
        
    - name: Install dependencies (Web)
      run: |
        cd web
        npm ci
        
    - name: Lint Bot
      run: |
        cd bot
        npm run build
        
    - name: Lint Web
      run: |
        cd web
        npm run lint
        npm run build
        
  deploy-development:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies (Bot)
      run: |
        cd bot
        npm ci
        
    - name: Install dependencies (Web)
      run: |
        cd web
        npm ci
        
    - name: Build Bot
      run: |
        cd bot
        npm run build
        
    - name: Deploy to Firebase (Development)
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LINE_KAKEIBO_0410 }}
        projectId: line-kakeibo-0410
        channelId: develop
        
    - name: Deploy to Vercel (Preview)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./web
        scope: ${{ secrets.VERCEL_ORG_ID }}
        
    - name: Comment PR with Preview URLs
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { context } = require('@actions/github');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚀 **Development Environment Deployed!**\n\n📱 Vercel Preview: Check deploy status\n🔥 Firebase Preview: Check deploy status\n\n_This comment will be updated with URLs once deployment completes._'
          });